/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditLogsIndexRouteImport } from './routes/audit-logs/index'
import { Route as MiningRoomsIndexRouteImport } from './routes/mining-rooms/index'
import { Route as MiningRoomsIdRouteImport } from './routes/mining-rooms/$id'
import { Route as MiningRoundsIndexRouteImport } from './routes/mining-rounds/index'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as TicketsIdRouteImport } from './routes/tickets/$id'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersIdRouteImport } from './routes/users/$id'
import { Route as WithdrawalsIndexRouteImport } from './routes/withdrawals/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsIndexRoute = AuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningRoomsIndexRoute = MiningRoomsIndexRouteImport.update({
  id: '/mining-rooms/',
  path: '/mining-rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningRoomsIdRoute = MiningRoomsIdRouteImport.update({
  id: '/mining-rooms/$id',
  path: '/mining-rooms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningRoundsIndexRoute = MiningRoundsIndexRouteImport.update({
  id: '/mining-rounds/',
  path: '/mining-rounds/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalsIndexRoute = WithdrawalsIndexRouteImport.update({
  id: '/withdrawals/',
  path: '/withdrawals/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mining-rooms/$id': typeof MiningRoomsIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/audit-logs/': typeof AuditLogsIndexRoute
  '/mining-rooms/': typeof MiningRoomsIndexRoute
  '/mining-rounds/': typeof MiningRoundsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/withdrawals/': typeof WithdrawalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mining-rooms/$id': typeof MiningRoomsIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/audit-logs': typeof AuditLogsIndexRoute
  '/mining-rooms': typeof MiningRoomsIndexRoute
  '/mining-rounds': typeof MiningRoundsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/users': typeof UsersIndexRoute
  '/withdrawals': typeof WithdrawalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mining-rooms/$id': typeof MiningRoomsIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/audit-logs/': typeof AuditLogsIndexRoute
  '/mining-rooms/': typeof MiningRoomsIndexRoute
  '/mining-rounds/': typeof MiningRoundsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/withdrawals/': typeof WithdrawalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mining-rooms/$id'
    | '/tickets/$id'
    | '/users/$id'
    | '/audit-logs/'
    | '/mining-rooms/'
    | '/mining-rounds/'
    | '/roles/'
    | '/settings/'
    | '/staff/'
    | '/tickets/'
    | '/transactions/'
    | '/users/'
    | '/withdrawals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mining-rooms/$id'
    | '/tickets/$id'
    | '/users/$id'
    | '/audit-logs'
    | '/mining-rooms'
    | '/mining-rounds'
    | '/roles'
    | '/settings'
    | '/staff'
    | '/tickets'
    | '/transactions'
    | '/users'
    | '/withdrawals'
  id:
    | '__root__'
    | '/'
    | '/mining-rooms/$id'
    | '/tickets/$id'
    | '/users/$id'
    | '/audit-logs/'
    | '/mining-rooms/'
    | '/mining-rounds/'
    | '/roles/'
    | '/settings/'
    | '/staff/'
    | '/tickets/'
    | '/transactions/'
    | '/users/'
    | '/withdrawals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MiningRoomsIdRoute: typeof MiningRoomsIdRoute
  TicketsIdRoute: typeof TicketsIdRoute
  UsersIdRoute: typeof UsersIdRoute
  AuditLogsIndexRoute: typeof AuditLogsIndexRoute
  MiningRoomsIndexRoute: typeof MiningRoomsIndexRoute
  MiningRoundsIndexRoute: typeof MiningRoundsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  WithdrawalsIndexRoute: typeof WithdrawalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs/': {
      id: '/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AuditLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining-rooms/': {
      id: '/mining-rooms/'
      path: '/mining-rooms'
      fullPath: '/mining-rooms/'
      preLoaderRoute: typeof MiningRoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining-rooms/$id': {
      id: '/mining-rooms/$id'
      path: '/mining-rooms/$id'
      fullPath: '/mining-rooms/$id'
      preLoaderRoute: typeof MiningRoomsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining-rounds/': {
      id: '/mining-rounds/'
      path: '/mining-rounds'
      fullPath: '/mining-rounds/'
      preLoaderRoute: typeof MiningRoundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawals/': {
      id: '/withdrawals/'
      path: '/withdrawals'
      fullPath: '/withdrawals/'
      preLoaderRoute: typeof WithdrawalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MiningRoomsIdRoute: MiningRoomsIdRoute,
  TicketsIdRoute: TicketsIdRoute,
  UsersIdRoute: UsersIdRoute,
  AuditLogsIndexRoute: AuditLogsIndexRoute,
  MiningRoomsIndexRoute: MiningRoomsIndexRoute,
  MiningRoundsIndexRoute: MiningRoundsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  WithdrawalsIndexRoute: WithdrawalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
