/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomAddressRouteImport } from './routes/custom-address'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MiningRouteRouteImport } from './routes/mining/route'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TransactionsRouteRouteImport } from './routes/transactions/route'
import { Route as TransferRouteRouteImport } from './routes/transfer/route'
import { Route as WalletRouteRouteImport } from './routes/wallet/route'
import { Route as MiningIndexRouteImport } from './routes/mining/index'
import { Route as MiningHistoryRouteImport } from './routes/mining/history'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as SecurityIndexRouteImport } from './routes/security/index'
import { Route as SecurityDevicesRouteImport } from './routes/security/devices'
import { Route as SecurityFreezeRouteImport } from './routes/security/freeze'
import { Route as SecurityTransferPasswordRouteImport } from './routes/security/transfer-password'
import { Route as SecurityTwoFactorRouteImport } from './routes/security/two-factor'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as TransactionsTransferIdRouteImport } from './routes/transactions/$transferId'
import { Route as TransferIndexRouteImport } from './routes/transfer/index'
import { Route as TransferRecipientsRouteImport } from './routes/transfer/recipients'
import { Route as WalletIndexRouteImport } from './routes/wallet/index'
import { Route as WalletAddressBookRouteImport } from './routes/wallet/address-book'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomAddressRoute = CustomAddressRouteImport.update({
  id: '/custom-address',
  path: '/custom-address',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningRouteRoute = MiningRouteRouteImport.update({
  id: '/mining',
  path: '/mining',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRouteRoute = TransactionsRouteRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRouteRoute = TransferRouteRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRouteRoute = WalletRouteRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningIndexRoute = MiningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MiningRouteRoute,
} as any)
const MiningHistoryRoute = MiningHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MiningRouteRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityDevicesRoute = SecurityDevicesRouteImport.update({
  id: '/security/devices',
  path: '/security/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityFreezeRoute = SecurityFreezeRouteImport.update({
  id: '/security/freeze',
  path: '/security/freeze',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityTransferPasswordRoute =
  SecurityTransferPasswordRouteImport.update({
    id: '/security/transfer-password',
    path: '/security/transfer-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const SecurityTwoFactorRoute = SecurityTwoFactorRouteImport.update({
  id: '/security/two-factor',
  path: '/security/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransactionsRouteRoute,
} as any)
const TransactionsTransferIdRoute = TransactionsTransferIdRouteImport.update({
  id: '/$transferId',
  path: '/$transferId',
  getParentRoute: () => TransactionsRouteRoute,
} as any)
const TransferIndexRoute = TransferIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransferRouteRoute,
} as any)
const TransferRecipientsRoute = TransferRecipientsRouteImport.update({
  id: '/recipients',
  path: '/recipients',
  getParentRoute: () => TransferRouteRoute,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRouteRoute,
} as any)
const WalletAddressBookRoute = WalletAddressBookRouteImport.update({
  id: '/address-book',
  path: '/address-book',
  getParentRoute: () => WalletRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mining': typeof MiningRouteRouteWithChildren
  '/transactions': typeof TransactionsRouteRouteWithChildren
  '/transfer': typeof TransferRouteRouteWithChildren
  '/wallet': typeof WalletRouteRouteWithChildren
  '/custom-address': typeof CustomAddressRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/mining/history': typeof MiningHistoryRoute
  '/security/devices': typeof SecurityDevicesRoute
  '/security/freeze': typeof SecurityFreezeRoute
  '/security/transfer-password': typeof SecurityTransferPasswordRoute
  '/security/two-factor': typeof SecurityTwoFactorRoute
  '/transactions/$transferId': typeof TransactionsTransferIdRoute
  '/transfer/recipients': typeof TransferRecipientsRoute
  '/wallet/address-book': typeof WalletAddressBookRoute
  '/mining/': typeof MiningIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/transfer/': typeof TransferIndexRoute
  '/wallet/': typeof WalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-address': typeof CustomAddressRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/mining/history': typeof MiningHistoryRoute
  '/security/devices': typeof SecurityDevicesRoute
  '/security/freeze': typeof SecurityFreezeRoute
  '/security/transfer-password': typeof SecurityTransferPasswordRoute
  '/security/two-factor': typeof SecurityTwoFactorRoute
  '/transactions/$transferId': typeof TransactionsTransferIdRoute
  '/transfer/recipients': typeof TransferRecipientsRoute
  '/wallet/address-book': typeof WalletAddressBookRoute
  '/mining': typeof MiningIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/security': typeof SecurityIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/transfer': typeof TransferIndexRoute
  '/wallet': typeof WalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mining': typeof MiningRouteRouteWithChildren
  '/transactions': typeof TransactionsRouteRouteWithChildren
  '/transfer': typeof TransferRouteRouteWithChildren
  '/wallet': typeof WalletRouteRouteWithChildren
  '/custom-address': typeof CustomAddressRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/mining/history': typeof MiningHistoryRoute
  '/security/devices': typeof SecurityDevicesRoute
  '/security/freeze': typeof SecurityFreezeRoute
  '/security/transfer-password': typeof SecurityTransferPasswordRoute
  '/security/two-factor': typeof SecurityTwoFactorRoute
  '/transactions/$transferId': typeof TransactionsTransferIdRoute
  '/transfer/recipients': typeof TransferRecipientsRoute
  '/wallet/address-book': typeof WalletAddressBookRoute
  '/mining/': typeof MiningIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/transfer/': typeof TransferIndexRoute
  '/wallet/': typeof WalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mining'
    | '/transactions'
    | '/transfer'
    | '/wallet'
    | '/custom-address'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/mining/history'
    | '/security/devices'
    | '/security/freeze'
    | '/security/transfer-password'
    | '/security/two-factor'
    | '/transactions/$transferId'
    | '/transfer/recipients'
    | '/wallet/address-book'
    | '/mining/'
    | '/profile/'
    | '/security/'
    | '/settings/'
    | '/transactions/'
    | '/transfer/'
    | '/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom-address'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/mining/history'
    | '/security/devices'
    | '/security/freeze'
    | '/security/transfer-password'
    | '/security/two-factor'
    | '/transactions/$transferId'
    | '/transfer/recipients'
    | '/wallet/address-book'
    | '/mining'
    | '/profile'
    | '/security'
    | '/settings'
    | '/transactions'
    | '/transfer'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/mining'
    | '/transactions'
    | '/transfer'
    | '/wallet'
    | '/custom-address'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/mining/history'
    | '/security/devices'
    | '/security/freeze'
    | '/security/transfer-password'
    | '/security/two-factor'
    | '/transactions/$transferId'
    | '/transfer/recipients'
    | '/wallet/address-book'
    | '/mining/'
    | '/profile/'
    | '/security/'
    | '/settings/'
    | '/transactions/'
    | '/transfer/'
    | '/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MiningRouteRoute: typeof MiningRouteRouteWithChildren
  TransactionsRouteRoute: typeof TransactionsRouteRouteWithChildren
  TransferRouteRoute: typeof TransferRouteRouteWithChildren
  WalletRouteRoute: typeof WalletRouteRouteWithChildren
  CustomAddressRoute: typeof CustomAddressRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SecurityDevicesRoute: typeof SecurityDevicesRoute
  SecurityFreezeRoute: typeof SecurityFreezeRoute
  SecurityTransferPasswordRoute: typeof SecurityTransferPasswordRoute
  SecurityTwoFactorRoute: typeof SecurityTwoFactorRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-address': {
      id: '/custom-address'
      path: '/custom-address'
      fullPath: '/custom-address'
      preLoaderRoute: typeof CustomAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining': {
      id: '/mining'
      path: '/mining'
      fullPath: '/mining'
      preLoaderRoute: typeof MiningRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining/': {
      id: '/mining/'
      path: '/'
      fullPath: '/mining/'
      preLoaderRoute: typeof MiningIndexRouteImport
      parentRoute: typeof MiningRouteRoute
    }
    '/mining/history': {
      id: '/mining/history'
      path: '/history'
      fullPath: '/mining/history'
      preLoaderRoute: typeof MiningHistoryRouteImport
      parentRoute: typeof MiningRouteRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/devices': {
      id: '/security/devices'
      path: '/security/devices'
      fullPath: '/security/devices'
      preLoaderRoute: typeof SecurityDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/freeze': {
      id: '/security/freeze'
      path: '/security/freeze'
      fullPath: '/security/freeze'
      preLoaderRoute: typeof SecurityFreezeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/transfer-password': {
      id: '/security/transfer-password'
      path: '/security/transfer-password'
      fullPath: '/security/transfer-password'
      preLoaderRoute: typeof SecurityTransferPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/two-factor': {
      id: '/security/two-factor'
      path: '/security/two-factor'
      fullPath: '/security/two-factor'
      preLoaderRoute: typeof SecurityTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof TransactionsRouteRoute
    }
    '/transactions/$transferId': {
      id: '/transactions/$transferId'
      path: '/$transferId'
      fullPath: '/transactions/$transferId'
      preLoaderRoute: typeof TransactionsTransferIdRouteImport
      parentRoute: typeof TransactionsRouteRoute
    }
    '/transfer/': {
      id: '/transfer/'
      path: '/'
      fullPath: '/transfer/'
      preLoaderRoute: typeof TransferIndexRouteImport
      parentRoute: typeof TransferRouteRoute
    }
    '/transfer/recipients': {
      id: '/transfer/recipients'
      path: '/recipients'
      fullPath: '/transfer/recipients'
      preLoaderRoute: typeof TransferRecipientsRouteImport
      parentRoute: typeof TransferRouteRoute
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof WalletRouteRoute
    }
    '/wallet/address-book': {
      id: '/wallet/address-book'
      path: '/address-book'
      fullPath: '/wallet/address-book'
      preLoaderRoute: typeof WalletAddressBookRouteImport
      parentRoute: typeof WalletRouteRoute
    }
  }
}

interface MiningRouteRouteChildren {
  MiningHistoryRoute: typeof MiningHistoryRoute
  MiningIndexRoute: typeof MiningIndexRoute
}

const MiningRouteRouteChildren: MiningRouteRouteChildren = {
  MiningHistoryRoute: MiningHistoryRoute,
  MiningIndexRoute: MiningIndexRoute,
}

const MiningRouteRouteWithChildren = MiningRouteRoute._addFileChildren(
  MiningRouteRouteChildren,
)

interface TransactionsRouteRouteChildren {
  TransactionsTransferIdRoute: typeof TransactionsTransferIdRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

const TransactionsRouteRouteChildren: TransactionsRouteRouteChildren = {
  TransactionsTransferIdRoute: TransactionsTransferIdRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}

const TransactionsRouteRouteWithChildren =
  TransactionsRouteRoute._addFileChildren(TransactionsRouteRouteChildren)

interface TransferRouteRouteChildren {
  TransferRecipientsRoute: typeof TransferRecipientsRoute
  TransferIndexRoute: typeof TransferIndexRoute
}

const TransferRouteRouteChildren: TransferRouteRouteChildren = {
  TransferRecipientsRoute: TransferRecipientsRoute,
  TransferIndexRoute: TransferIndexRoute,
}

const TransferRouteRouteWithChildren = TransferRouteRoute._addFileChildren(
  TransferRouteRouteChildren,
)

interface WalletRouteRouteChildren {
  WalletAddressBookRoute: typeof WalletAddressBookRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

const WalletRouteRouteChildren: WalletRouteRouteChildren = {
  WalletAddressBookRoute: WalletAddressBookRoute,
  WalletIndexRoute: WalletIndexRoute,
}

const WalletRouteRouteWithChildren = WalletRouteRoute._addFileChildren(
  WalletRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MiningRouteRoute: MiningRouteRouteWithChildren,
  TransactionsRouteRoute: TransactionsRouteRouteWithChildren,
  TransferRouteRoute: TransferRouteRouteWithChildren,
  WalletRouteRoute: WalletRouteRouteWithChildren,
  CustomAddressRoute: CustomAddressRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SecurityDevicesRoute: SecurityDevicesRoute,
  SecurityFreezeRoute: SecurityFreezeRoute,
  SecurityTransferPasswordRoute: SecurityTransferPasswordRoute,
  SecurityTwoFactorRoute: SecurityTwoFactorRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SecurityIndexRoute: SecurityIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
