/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomAddressRouteImport } from './routes/custom-address'
import { Route as HistoryRouteRouteImport } from './routes/history/route'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MiningRouteImport } from './routes/mining'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as HistoryTransferIdRouteImport } from './routes/history/$transferId'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as SecurityIndexRouteImport } from './routes/security/index'
import { Route as SecurityDevicesRouteImport } from './routes/security/devices'
import { Route as SecurityFreezeRouteImport } from './routes/security/freeze'
import { Route as SecurityTransferPasswordRouteImport } from './routes/security/transfer-password'
import { Route as SecurityTwoFactorRouteImport } from './routes/security/two-factor'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomAddressRoute = CustomAddressRouteImport.update({
  id: '/custom-address',
  path: '/custom-address',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRouteRoute = HistoryRouteRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningRoute = MiningRouteImport.update({
  id: '/mining',
  path: '/mining',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HistoryRouteRoute,
} as any)
const HistoryTransferIdRoute = HistoryTransferIdRouteImport.update({
  id: '/$transferId',
  path: '/$transferId',
  getParentRoute: () => HistoryRouteRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityDevicesRoute = SecurityDevicesRouteImport.update({
  id: '/security/devices',
  path: '/security/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityFreezeRoute = SecurityFreezeRouteImport.update({
  id: '/security/freeze',
  path: '/security/freeze',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityTransferPasswordRoute =
  SecurityTransferPasswordRouteImport.update({
    id: '/security/transfer-password',
    path: '/security/transfer-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const SecurityTwoFactorRoute = SecurityTwoFactorRouteImport.update({
  id: '/security/two-factor',
  path: '/security/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteRouteWithChildren
  '/custom-address': typeof CustomAddressRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mining': typeof MiningRoute
  '/transfer': typeof TransferRoute
  '/wallet': typeof WalletRoute
  '/history/$transferId': typeof HistoryTransferIdRoute
  '/security/devices': typeof SecurityDevicesRoute
  '/security/freeze': typeof SecurityFreezeRoute
  '/security/transfer-password': typeof SecurityTransferPasswordRoute
  '/security/two-factor': typeof SecurityTwoFactorRoute
  '/history/': typeof HistoryIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-address': typeof CustomAddressRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mining': typeof MiningRoute
  '/transfer': typeof TransferRoute
  '/wallet': typeof WalletRoute
  '/history/$transferId': typeof HistoryTransferIdRoute
  '/security/devices': typeof SecurityDevicesRoute
  '/security/freeze': typeof SecurityFreezeRoute
  '/security/transfer-password': typeof SecurityTransferPasswordRoute
  '/security/two-factor': typeof SecurityTwoFactorRoute
  '/history': typeof HistoryIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/security': typeof SecurityIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteRouteWithChildren
  '/custom-address': typeof CustomAddressRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mining': typeof MiningRoute
  '/transfer': typeof TransferRoute
  '/wallet': typeof WalletRoute
  '/history/$transferId': typeof HistoryTransferIdRoute
  '/security/devices': typeof SecurityDevicesRoute
  '/security/freeze': typeof SecurityFreezeRoute
  '/security/transfer-password': typeof SecurityTransferPasswordRoute
  '/security/two-factor': typeof SecurityTwoFactorRoute
  '/history/': typeof HistoryIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/custom-address'
    | '/leaderboard'
    | '/mining'
    | '/transfer'
    | '/wallet'
    | '/history/$transferId'
    | '/security/devices'
    | '/security/freeze'
    | '/security/transfer-password'
    | '/security/two-factor'
    | '/history/'
    | '/profile/'
    | '/security/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom-address'
    | '/leaderboard'
    | '/mining'
    | '/transfer'
    | '/wallet'
    | '/history/$transferId'
    | '/security/devices'
    | '/security/freeze'
    | '/security/transfer-password'
    | '/security/two-factor'
    | '/history'
    | '/profile'
    | '/security'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/custom-address'
    | '/leaderboard'
    | '/mining'
    | '/transfer'
    | '/wallet'
    | '/history/$transferId'
    | '/security/devices'
    | '/security/freeze'
    | '/security/transfer-password'
    | '/security/two-factor'
    | '/history/'
    | '/profile/'
    | '/security/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRouteRoute: typeof HistoryRouteRouteWithChildren
  CustomAddressRoute: typeof CustomAddressRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MiningRoute: typeof MiningRoute
  TransferRoute: typeof TransferRoute
  WalletRoute: typeof WalletRoute
  SecurityDevicesRoute: typeof SecurityDevicesRoute
  SecurityFreezeRoute: typeof SecurityFreezeRoute
  SecurityTransferPasswordRoute: typeof SecurityTransferPasswordRoute
  SecurityTwoFactorRoute: typeof SecurityTwoFactorRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-address': {
      id: '/custom-address'
      path: '/custom-address'
      fullPath: '/custom-address'
      preLoaderRoute: typeof CustomAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining': {
      id: '/mining'
      path: '/mining'
      fullPath: '/mining'
      preLoaderRoute: typeof MiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof HistoryRouteRoute
    }
    '/history/$transferId': {
      id: '/history/$transferId'
      path: '/$transferId'
      fullPath: '/history/$transferId'
      preLoaderRoute: typeof HistoryTransferIdRouteImport
      parentRoute: typeof HistoryRouteRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/devices': {
      id: '/security/devices'
      path: '/security/devices'
      fullPath: '/security/devices'
      preLoaderRoute: typeof SecurityDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/freeze': {
      id: '/security/freeze'
      path: '/security/freeze'
      fullPath: '/security/freeze'
      preLoaderRoute: typeof SecurityFreezeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/transfer-password': {
      id: '/security/transfer-password'
      path: '/security/transfer-password'
      fullPath: '/security/transfer-password'
      preLoaderRoute: typeof SecurityTransferPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/two-factor': {
      id: '/security/two-factor'
      path: '/security/two-factor'
      fullPath: '/security/two-factor'
      preLoaderRoute: typeof SecurityTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HistoryRouteRouteChildren {
  HistoryTransferIdRoute: typeof HistoryTransferIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

const HistoryRouteRouteChildren: HistoryRouteRouteChildren = {
  HistoryTransferIdRoute: HistoryTransferIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}

const HistoryRouteRouteWithChildren = HistoryRouteRoute._addFileChildren(
  HistoryRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRouteRoute: HistoryRouteRouteWithChildren,
  CustomAddressRoute: CustomAddressRoute,
  LeaderboardRoute: LeaderboardRoute,
  MiningRoute: MiningRoute,
  TransferRoute: TransferRoute,
  WalletRoute: WalletRoute,
  SecurityDevicesRoute: SecurityDevicesRoute,
  SecurityFreezeRoute: SecurityFreezeRoute,
  SecurityTransferPasswordRoute: SecurityTransferPasswordRoute,
  SecurityTwoFactorRoute: SecurityTwoFactorRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SecurityIndexRoute: SecurityIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
